config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :mining_types
  resources :moedas
  resources :home
  resources :hello
  resources :welcome
  get 'home/html'
  get 'welcome/index'
  get 'hello/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :moedas
end

app/models/moeda.rb
class Moeda < ApplicationRecord
  belongs_to :mining_type#, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end
# muda para o ingles ou portugues

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
    @nome = "Fulano"
    @curso = params[:meu_curso]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def html
  end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  # GET /mining_types
  # GET /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1
  # GET /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types
  # POST /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1
  # PATCH/PUT /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1
  # DELETE /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  ################################3
    #Use callbacks to share common setup or constraints between actions.
   def set_mining_type
     @mining_type = MiningType.find(params[:id])
   end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mining_type_params
      params.require(:mining_type).permit(:name, :acronym)
    end
end

app/controllers/moedas_controller.rb
class MoedasController < ApplicationController

  before_action :set_moeda, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type_options, only: [:new,:create, :edit, :update]

  # GET /moedas
  # GET /moedas.json
  def index
    @moedas = Moeda.all
  end

  # GET /moedas/1
  # GET /moedas/1.json
  # GET /moedas/new
  def new
    @moeda = Moeda.new
  end

  # GET /moedas/1/edit
  def edit
  end

  # POST /moedas
  # POST /moedas.json
  def create
    @moeda = Moeda.new(moeda_params)

    respond_to do |format|
      if @moeda.save
        format.html { redirect_to @moeda, notice: 'Moeda was successfully created.' }
        format.json { render :show, status: :created, location: @moeda }
      else
        format.html { render :new }
        format.json { render json: @moeda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moedas/1
  # PATCH/PUT /moedas/1.json
  def update
    respond_to do |format|
      if @moeda.update(moeda_params)
        format.html { redirect_to @moeda, notice: 'Moeda was successfully updated.' }
        format.json { render :show, status: :ok, location: @moeda }
      else
        format.html { render :edit }
        format.json { render json: @moeda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moedas/1
  # DELETE /moedas/1.json
  def destroy
    @moeda.destroy
    respond_to do |format|
      format.html { redirect_to moedas_url, notice: 'Moeda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_mining_type_options
    @mining_type_options = MiningType.all.pluck(:name, :id)#####################33
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_moeda
      @moeda = Moeda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moeda_params
      params.require(:moeda).permit(:description, :acronym, :url_image, :mining_types_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de Ruby on Rails - cookie ### "
    session[:curso] = "Aluno Vander - sesseion"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
    data_us.strftime("%d/%m/%Y")
  end

  def locale(loacle)
    if I18n.locale == :en
      "Usa"
    else
      "Portugues-BR"
    end
  end

  def nome_aplicacao
    "Cripto moeda"
  end

  def ambiente

  if Rails.env.development?
    "Desenvolvimento"


  elsif Rails.env.prodution?
    "Produçao"

  else
    "Teste"
  end
  end
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/moedas_helper.rb
module MoedasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hello/_menu_html.erb
<ul>
  <li>
     Home <br>
    <%= link_to "Bem vindos" , "/welcome"%>
  </li>
</ul>

app/views/hello/index.html.erb
<h1>Hello</h1>
<p>Voce esta em ambinete de <strong><%=Rails.env %></strong></p>
<p>Voce esta em ambinete de <strong><%= ambiente %></strong></p>
<p>Sou  uma variavel de sessao:<%= @nome %></p>
<h3><%= render 'hello/menu_html' %></h3>

app/views/layouts/adm.html.erb
##########################

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1> TESTE LAYOUT EM TODAS AS PAGINAS </h1>
    <%= yield %>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1>Editing Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Show', @mining_type %> |
<%= link_to 'Back', mining_types_path %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Acronym</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.name %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to "Mostrar", mining_type %></td>
        <td><%= link_to "Editar", edit_mining_type_path(mining_type) %></td>
        <td><%= link_to "Apagar", mining_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mining Type', new_mining_type_path %>

app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mining_type.name %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to 'Edit', edit_mining_type_path(@mining_type) %> |
<%= link_to 'Back', mining_types_path %>

app/views/moedas/_form.html.erb
<%= form_with(model: moeda, local: true) do |form| %>
  <% if moeda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(moeda.errors.count, "error") %> prohibited this moeda from being saved:</h2>

      <ul>
      <% moeda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= data_br(Date.today)%> <br><br><%= nome_aplicacao %><br><br>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
  </div>

  <div class="field">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type_options, {include_blank: 'Selecione...'}) %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moedas/edit.html.erb
<h1>Editing Moeda</h1>

<%= render 'form', moeda: @moeda %>

<%= link_to 'Show', @moeda %> |
<%= link_to 'Back', moedas_path %>

app/views/moedas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moedas</h1>
<%= data_br(Date.today)%><br>
<%= nome_aplicacao %><br>
<%= cookies[:curso]%>
<table>
  <thead>
    <tr>
      <th><%=@moedas.human_attribute_name(:description)%></th>
      <th><%=@moedas.human_attribute_name(:acronym)%></th>
      <th><%=@moedas.human_attribute_name(:url_image)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moedas.each do |moeda| %>
      <tr>
        <td><%= moeda.description %></td>
        <td><%= moeda.acronym %></td>
        <td><%= moeda.url_image %></td>
        <td><img src="<%= moeda.url_image %>" width="50px" height="50px"></td>
        <td><%= link_to "Mostrar", moeda %></td> <!---t(links.show) traduções--->
        <td><%= link_to "Editar", edit_moeda_path(moeda) %></td>
        <td><%= link_to "Deletar", moeda, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
        <br>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Moeda', new_moeda_path %>

app/views/moedas/new.html.erb
<h1>New Moeda</h1>

<%= render 'form', moeda: @moeda %>

<%= link_to 'Back', moedas_path %>

app/views/moedas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @moeda.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @moeda.acronym %>
</p>

<p>
  <strong>Url image:</strong>
  <%= @moeda.url_image %>
</p>

<%= link_to 'Edit', edit_moeda_path(@moeda) %> |
<%= link_to 'Back', moedas_path %>

app/views/welcome/_menu.html.erb
<h2><%= link_to 'Moeda', moedas_path %></h2>
<br><br>
<h2><%= link_to "#{MiningType.model_name.human}", mining_types_path, class:"btn btn-primary btn-lg", role:"button"%></h2>

app/views/welcome/index.html.erb
<!--<h1>Seja bem vindo</h1>-->
<%#= data_br(Date.today)%>
<!--<p><strong>A data de hoje é: </strong> <%#= data_br(Date.today)%> </p>-->
<!--<h1>Vander Quintanilha</h1>-->
<!--<p> A soma é : <%#= 1 + 1 =%> </p>-->
<!--<p> Seu nome de tras para frente é: <%#= "Vander".reverse=%> </p>-->
<%# a= "minha variavel" %>
<!--<p> Imprimrndo a variavel: <%#= a =%> </p>-->
<!--<p> A data de hoje é: <%#= Date.today %> </p>-->

<!--<ul>-->
<!--  <li>-->
<!--    <a href="www.google.com.br">Google</a> <br>-->
<!--    <a href="http://localhost:3000/moedas">Cadastro de Moedas</a><br>-->
    <%#= link_to "Cadastro de moedas" , "/moedas"%>
    <%#= %>
<!--  </li>-->
<!--  <li>-->
   <%#= link_to "Home" , "/welcome"%>
<!--  </li>-->
<!--   <br>-->
<!--    <img src="https://img.ibxk.com.br/2018/08/29/29194642940337.jpg?w=1120&h=420&mode=crop&scale=both" width="500px" height="400px" />-->
<!--</ul>-->

<div class="jumbotron">
  <p>idioma:<%= locale(I18n.locale)%> </p><!---Tradução----> <!---Na viw pode ser t("chave")-->

 <strong><%=I18n.l(Date.today)%></strong> <!---Transformando data local---->
  <p>
    <%= link_to 'Idiomas portugues', '/?locale=pt-BR'%>
  </p>
  <p>
    <%= link_to 'English', '/?locale=en'%>
  </p>
  <p><%= I18n.t("abc") %></p>
  <br><br>
  <h1 class="display-4"><%= t('Bem vindos') %></h1><br>
  <h2 class="lead"><%= t('messages.cripto moedas')%></h2>
  <hr class="my-4">
  <p><%= t('messages.menu')%></p>
  <h3><%= render "menu" %></h3>
  <br>
  <hr class="my-4">
</div>

<!--# adicionando relacionamento entre tabelas-->


<!--rails g migration AddMiningTypeToTabelas->-->
<!--mining_tabela:references-->